### ISSUE TITLE
ignite v28.5.0 panic

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#421]
The following panic occurs on the wordle tutorial if you run with v28.5.0 

```
 rollkit start --rollkit.aggregator --rollkit.da_address http://localhost:7980
panic: proto: could not resolve import "core/crypto/pb/crypto.proto": not found

goroutine 1 [running]:
github.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.newModuleQuerySafeAllowList()
	/Users/matt/Code/go/pkg/mod/github.com/cosmos/ibc-go/v8@v8.3.1/modules/apps/27-interchain-accounts/host/keeper/keeper.go:287 +0x76
github.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.NewKeeper({_, _}, {_, _}, {_, _}, {_, _}, {0x104edb8e0, 0xc0010ed7a0}, ...)
	/Users/matt/Code/go/pkg/mod/github.com/cosmos/ibc-go/v8@v8.3.1/modules/apps/27-interchain-accounts/host/keeper/keeper.go:82 +0xbc
wordle/app.(*App).registerIBCModules(0xc002090008, {0x104f02000?, 0xc0002074c0?})
	/Users/matt/Code/test/wordle/app/ibc.go:118 +0x21de
wordle/app.New({0x104ee6560, 0xc0005c4cb0}, {0x104f02000, 0xc0002074c0}, {0x0, 0x0}, 0x1, {0x104e9c600, 0xc000e0e8c0}, {0xc0003f4d90, ...})
	/Users/matt/Code/test/wordle/app/app.go:261 +0x878
wordle/cmd/wordled/cmd.newApp({0x104ee6560, 0xc0005c4cb0}, {0x104f02000, 0xc0002074c0}, {0x0, 0x0}, {0x104e9c600, 0xc000e0e8c0})
	/Users/matt/Code/test/wordle/cmd/wordled/cmd/commands.go:140 +0xaa
github.com/rollkit/cosmos-sdk-starter/server.startApp[...](0xc0000d61a0, 0x104e86600, {0x104e86d28, 0x0, 0x0, 0x104e865f8, 0x104e865e0})
	/Users/matt/Code/go/pkg/mod/github.com/rollkit/cosmos-sdk-starter@v0.0.0-20240711025550-2ec636be897c/server/start.go:77 +0x17c
github.com/rollkit/cosmos-sdk-starter/server.StartHandler[...](_, {{0x0, 0x0, 0x0}, {0x104f08358, 0xc00119e5d0}, 0x0, {0x0, 0x0}, {0x104f2a890, ...}, ...}, ...)
	/Users/matt/Code/go/pkg/mod/github.com/rollkit/cosmos-sdk-starter@v0.0.0-20240711025550-2ec636be897c/server/start.go:49 +0x185
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	/Users/matt/Code/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.8/server/start.go:198 +0x63
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc0000d61a0, 0xc000f299f8)
	/Users/matt/Code/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.8/server/start.go:570 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc000c7c908, {0xc0014a7a90?, 0x0?, 0x5?})
	/Users/matt/Code/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.8/server/start.go:197 +0x212
github.com/spf13/cobra.(*Command).execute(0xc000c7c908, {0xc0014a7a40, 0x5, 0x5})
	/Users/matt/Code/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0014cfb08)
	/Users/matt/Code/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/matt/Code/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/matt/Code/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc0014cfb08, {0x0, 0x0}, {0x7ff7bf49e4ed, 0x13})
	/Users/matt/Code/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.8/server/cmd/execute.go:34 +0x187
main.main()
	/Users/matt/Code/test/wordle/cmd/wordled/main.go:15 +0x33
Error intercepting command:  failed to run entrypoint: exit status 2
```

we should keep the tutorial on v28.4.0 until we can resolve this issue. 

Commenting out lines 261-263 in wordle/app/app.go get around the panic, but the effects of that are unknown.

**Comment by jcstein** [comment]
i'm getting the same panic and cannot figure out the workaround

see telegram chat for more info, summary is:

```shell
% rollkit start \
    --rollkit.aggregator \
    --rollkit.da_auth_token $AUTH_TOKEN \
    --rollkit.da_namespace $DA_NAMESPACE \
    --rollkit.da_start_height $DA_BLOCK_HEIGHT \
    --minimum-gas-prices="0.025stake" \
    --rollkit.da_address http://localhost:26658
    
panic: proto: could not resolve import "core/crypto/pb/crypto.proto": not found

goroutine 1 [running]:
github.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.newModuleQuerySafeAllowList()
	/Users/js/go/pkg/mod/github.com/cosmos/ibc-go/v8@v8.3.1/modules/apps/27-interchain-accounts/host/keeper/keeper.go:287 +0x7c
github.com/cosmos/ibc-go/v8/modules/apps/27-interchain-accounts/host/keeper.NewKeeper({0x1068a6528, _}, {_, _}, {_, _}, {_, _}, {_, _}, ...)
	/Users/js/go/pkg/mod/github.com/cosmos/ibc-go/v8@v8.3.1/modules/apps/27-interchain-accounts/host/keeper/keeper.go:82 +0xa4
gm/app.(*App).registerIBCModules(0x1400087b608, {0x10687ed28?, 0x140000b0050?})
	/Users/js/gm/app/ibc.go:118 +0x1b30
gm/app.New({0x106864728, 0x14000c043f0}, {0x10687ed28, 0x140000b0050}, {0x0, 0x0}, 0x1, {0x10681b620, 0x14000e50000}, {0x14000c044d0, ...})
	/Users/js/gm/app/app.go:259 +0x604
gm/cmd/gmd/cmd.newApp({0x106864728, 0x14000c043f0}, {0x10687ed28, 0x140000b0050}, {0x0, 0x0}, {0x10681b620, 0x14000e50000})
	/Users/js/gm/cmd/gmd/cmd/commands.go:140 +0x78
github.com/rollkit/cosmos-sdk-starter/server.startApp[...](0x14001521ec0, 0x106805ba8, {0x1068062e0, 0x0, 0x0, 0x106805ba0, 0x106805b88})
	/Users/js/go/pkg/mod/github.com/rollkit/cosmos-sdk-starter@v0.0.0-20240826100644-1c45500296f4/server/start.go:77 +0x150
github.com/rollkit/cosmos-sdk-starter/server.StartHandler[...](_, {{0x0, 0x0, 0x0}, {0x1068866b0, 0x140008808d0}, 0x0, {0x0, 0x0}, {0x1068a6528, ...}, ...}, ...)
	/Users/js/go/pkg/mod/github.com/rollkit/cosmos-sdk-starter@v0.0.0-20240826100644-1c45500296f4/server/start.go:49 +0xe8
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	/Users/js/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:198 +0x68
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0x14001521ec0, 0x1400150f9d8)
	/Users/js/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:570 +0x16c
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0x140013fb808, {0x140008ce780?, 0x0?, 0xc?})
	/Users/js/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:197 +0x184
github.com/spf13/cobra.(*Command).execute(0x140013fb808, {0x140008ce480, 0xc, 0xc})
	/Users/js/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14001217b08)
	/Users/js/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/js/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/js/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x14001217b08, {0x104e71fd1, 0x2}, {0x16d71f8bb, 0xd})
	/Users/js/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/server/cmd/execute.go:34 +0x154
main.main()
	/Users/js/gm/cmd/gmd/main.go:16 +0x44
Error intercepting command:  failed to run entrypoint: exit status 2
```

**Comment by jcstein** [comment]
The workaround may be using ignite 28.4.0 from [telegram message](https://t.me/rollkit/1705) by @a26nine

**Comment by a26nine** [comment]
Root cause: https://github.com/ignite/cli/issues/4318
